# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            My Dev Blog
tagline:          A bunch of random stuff I do With my life
url:              http://aep000.github.io
paginate:         1
baseurl:          /
author:
  name:           Alex
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
