# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Alex's Blog
tagline:          'A blog about the random things I do'
description:      A blog about things I do
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Alex'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
